"""
incident_pdf.py
Generates a formal Incident Report PDF for JA.PREMIER Security Agency.
Used by both the admin dashboard (download button per report).
Requires: fpdf2  →  pip install fpdf2
"""

from fpdf import FPDF
import os


def clean_text(text):
    """Normalize text to avoid FPDF Unicode errors."""
    if text is None:
        return ""
    return (
        str(text)
        .replace("—", "-")
        .replace("–", "-")
        .replace("’", "'")
        .replace("“", '"')
        .replace("”", '"')
        .replace("…", "...")
    )


def generate_incident_pdf(report: dict) -> bytes:
    """
    Accept a dict with keys:
        Submitted_At, Reported_By, Site,
        Who, What, Incident_DateTime, Where, How,
        Action_Taken, Status
    Returns raw PDF bytes.
    """

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    base_path = os.path.dirname(os.path.abspath(__file__))
    logo_path = os.path.join(base_path, "agency_logo.png")

    # ── HEADER ───────────────────────────────────────────────────────────────
    if os.path.exists(logo_path):
        pdf.image(logo_path, x=10, y=10, w=25)

    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(0, 31, 63)  # navy
    pdf.set_xy(38, 12)
    pdf.cell(0, 7, "JA.PREMIER SECURITY AGENCY", ln=True)

    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(100, 100, 100)
    pdf.set_x(38)
    pdf.cell(0, 5, "Incident Report - CONFIDENTIAL", ln=True)

    pdf.set_draw_color(0, 31, 63)
    pdf.set_line_width(0.8)
    pdf.line(10, 38, 200, 38)
    pdf.ln(6)

    # ── REPORT TITLE ─────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(220, 53, 69)  # red
    pdf.cell(0, 8, "INCIDENT REPORT", ln=True, align="C")
    pdf.ln(2)

    # ── META INFO BOX ────────────────────────────────────────────────────────
    pdf.set_fill_color(240, 240, 245)
    pdf.set_draw_color(200, 200, 210)
    pdf.set_line_width(0.3)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(50, 50, 50)

    def meta_row(label, value):
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(0, 31, 63)
        pdf.cell(40, 6, clean_text(label), border=0)

        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(50, 50, 50)
        pdf.cell(0, 6, clean_text(value) if value else "-", border=0, ln=True)

    meta_row("Submitted At :", report.get("Submitted_At", "-"))
    meta_row("Reported By  :", report.get("Reported_By", "-"))
    meta_row("Site         :", report.get("Site", "-"))
    meta_row("Incident Date:", report.get("Incident_DateTime", "-"))
    meta_row("Status       :", report.get("Status", "NEW"))
    pdf.ln(4)

    # ── SECTION HELPER ───────────────────────────────────────────────────────
    def section(icon_label, content):
        # Header
        pdf.set_fill_color(0, 31, 63)
        pdf.set_text_color(255, 255, 255)
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 7, clean_text(f"  {icon_label}"), ln=True, fill=True)

        # Content
        pdf.set_fill_color(250, 250, 252)
        pdf.set_text_color(40, 40, 40)
        pdf.set_font("Helvetica", "", 10)

        safe_content = clean_text(content).strip() if content else "-"
        pdf.multi_cell(0, 6, safe_content, border=1, fill=True)
        pdf.ln(3)

    section("WHO was involved?", report.get("Who", ""))
    section("WHAT happened?", report.get("What", ""))
    section("WHERE did it happen?", report.get("Where", ""))
    section("HOW did it happen?", report.get("How", ""))
    section("Action Taken", report.get("Action_Taken", ""))

    # ── SIGNATURE BLOCK ──────────────────────────────────────────────────────
    pdf.ln(6)
    pdf.set_draw_color(180, 180, 180)
    pdf.set_line_width(0.3)
    pdf.line(10, pdf.get_y(), 95, pdf.get_y())
    pdf.line(115, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(2)

    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(85, 5, "Guard on Duty Signature / Printed Name", align="C")
    pdf.cell(20, 5, "")
    pdf.cell(85, 5, "Supervisor / Reviewed By", align="C")
    pdf.ln(8)

    # ── FOOTER ───────────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "I", 7)
    pdf.set_text_color(160, 160, 160)
    pdf.multi_cell(
        0,
        5,
        clean_text(
            "This document is auto-generated by the JA.PREMIER Guard Portal System. "
            "For official use only."
        ),
        align="C"
    )

    return bytes(pdf.output())
